version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
      - "8080:8080"
    volumes:
      - ./photos:/app/photos
    restart: unless-stopped

  frontend:
    build: ./client-ns-photobooth
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
